name: Database Maintenance

on:
  # run daily
  schedule:
    - cron: "0 6/12 * * *"
  # allow manual runs from GH
  workflow_dispatch:

env:
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  TURSO_DB_TABLE: ${{ secrets.TURSO_DB_TABLE }}
  TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
  TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
  EXPORT_FILE_NAME: "bigred-links-db-backup.json"
  EXPORT_FILE_DIR: "./"

permissions:
  contents: write

jobs:
  back-up-db:
    runs-on: ubuntu-latest
    steps:
      - name: 👷  Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: 🏗️  Setup Node.js ${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true

      - name: 📦  Install dependencies
        run: npm install

      - name: 🏃‍♂️  Run script to back up the database
        run: npm run back-up-db

      - name: 📎  Attach DB export JSON to workflow run
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.EXPORT_FILE_NAME }}
          path: ${{ env.EXPORT_FILE_DIR }}${{ env.EXPORT_FILE_NAME }}
          retention-days: 90
